server:
  port: 8084
spring:
  application:
    name: goods-service
  data:
    elasticsearch:
      cluster-nodes: 192.168.58.132:9300
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.58.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15

